### ISSUE TITLE
venial v0.5 release

### ISSUE THREAD

**Issue by Bromeon** [PoignardAzur/venial#32]
Would it be possible to release a crates.io version some time in September?

There have been quite a few features going into venial since v0.4, and it would be nice if other published crates could make use of them. Personally I plan to release a first version of godot-rust (GDExtension) in the near future, and this is not possible on crates.io with Git dependencies.

Once everything becomes more stable and forward-compatibility is a topic, `#[non_exhaustive]` could be applied to structs/enums as well. This could also be done in a v0.6 after getting some feedback from v0.5 (which will likely lead to some breaking changes). In that light, I'd also argue it's better to get a version out soon, advertise it and collect user input, rather than trying to find the perfect API in the darkness 😉 

One feature I still plan on implementing are `trait`s. Should be relatively quick to do as a lot of the foundation is now built, but it might make sense to have `mod` support merged first (https://github.com/PoignardAzur/venial/pull/31).

**Comment by PoignardAzur** [comment]
Sorry for not getting back to you.

Yes, a new release makes sense. I'll give it my undivided attention on Thursday and we'll see it through.

**Comment by Bromeon** [comment]
Thanks a lot, appreciate the trust! ❤️ 

I'm not crazy time-constrained, so would appreciate to polish a few things with you before release.
Maybe middle to end of October or so would be nice; I don't know about your availability though.

At some point, we might also look into publishing via CI, i.e. tagging `0.5.0` would invoke `cargo publish` (after manual confirmation, where you can choose who has the rights). I've [implemented this in godot-rust](https://github.com/godot-rust/godot-rust/blob/master/.github/workflows/release-version.yml), where things are more complex due to multi-crate workspace. What I would need from you is to create an API key on crates.io and store that in a GitHub secret. I would _not_ need to know the secret, just the name of the variable. This would not require direct crates.io access from other contributors, and you can selectively choose who can approve the deployment.

But this can also be added at any later stage, up to you 🙂

**Comment by PoignardAzur** [comment]
New version released.

**Comment by Bromeon** [comment]
Very nice, thanks a lot for this! 👍 

Do you want to make an announcement on Reddit/Twitter or so?

**Comment by PoignardAzur** [comment]
I'm not super invested either way.

**Comment by Bromeon** [comment]
I could also announce it 😉 but as you wish.

Mid-term, does it make sense if we look for other contributors/maintainers? I'm not sure I will have the capacity once the GDExtension/Rust port is available, as I expect lots of upcoming issues in the early phase. Plus, I also help maintain [SFML](https://github.com/SFML/SFML)...

**Comment by PoignardAzur** [comment]
(I noticed! Reading the SFML forums was a blast to the past. My posts from 2012 are still there!)

I'm not too worried about looking for maintainers. The userbase of the project is still tiny, and the project itself has a small enough surface area that I feel I should be able to fix bugs as they come up (with a bit of a delay).

If the project suddenly gets a popularity boost as more than a curiosity, then I expect more potential maintainers to show up.
