### ISSUE TITLE
Implement `span()` for each struct

### ISSUE THREAD

**Issue by rambip** [PoignardAzur/venial#46]
I really appreciate your work: the library is really clean and the user is not lost in details.

There is one feature missing I think: your structs don't have `span` methods

Say I want to create a macro to read unit_tests.
While parsing, I read `#[no_mangle]`, but this keyword is not legal here.
I would like to report an error to the user, saying "the attribute no_mangle is not allowed", and with the right span.

It would be really nice !

**Comment by PoignardAzur** [comment]
It's been a while since I've looked at macro code, but I think you can make these error messages using the `ToTokens` implementations? Do you specifically need a `span()` method?
